{% set name = "pymt_geotiff" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f82c5ff602fe0b3648386667fe5a95e5f23dfaffb5378a5f03bbf0d9e9fa16c4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - bmi-geotiff

test:
  requires:
    - bmi-tester
  imports:
    - pymt_geotiff
  commands:
    - bmi-test pymt_geotiff.bmi:GeoTiff -vvv  # [unix]

about:
  home: https://github.com/pymt-lab/pymt_geotiff
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Provides access to data and metadata from a GeoTIFF file within *pymt*.
  description: |
    *pymt_geotiff* is a Python package for a Python Modeling Toolkit (*pymt*)
    component that provides access to the data and metadata of a GeoTIFF file
    through *xarray* and *rasterio*.
  doc_url: https://pymt-geotiff.readthedocs.io
  dev_url: https://github.com/pymt-lab/pymt_geotiff

extra:
  recipe-maintainers:
    - mdpiper
